on:
  push:
    branches:
      - master
  label:
    types: 
      - created
  issues:
    types: [opened, labeled]    



jobs:
  print_hello:       
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
